Message.create!([
  {text: "Can i tryout? I play Jett Phoenix and Breach and am radiant rank", user_id: 5, conversation_id: 1},
  {text: "um yes lol can you play at 7pm est? and whats ur riot ID", user_id: 1, conversation_id: 1},
  {text: "ya jenja #4323 add me", user_id: 5, conversation_id: 1},
  {text: "Hey im new as well and kind of sick of the toxicity in solo q'ing. Can i join you? im also just learning the game", user_id: 6, conversation_id: 2},
  {text: "Yeah as long as ur chill with me being completely new to the game lmao. Im just tryna chill and learn the game man but keep getting yelled at by randoms. My riot ID is VicBoi #4444", user_id: 10, conversation_id: 2},
  {text: "Same bro, i added you! when u tryna play?", user_id: 6, conversation_id: 2},
  {text: "Good to play now if you are, i sent invite", user_id: 10, conversation_id: 2},
  {text: "Hi id like to join u", user_id: 3, conversation_id: 3},
  {text: "hey i want to join you, i think we could make a good team.", user_id: 4, conversation_id: 4},
  {text: "sounds good send me a friend request in game and we can play", user_id: 10, conversation_id: 4},
  {text: "hey, do you still have a spot? I am down to join you, tired of solo q-ing. Im currently plat 3", user_id: 2, conversation_id: 5},
  {text: "hey, great! what agent do you play as?", user_id: 8, conversation_id: 5},
  {text: "I mainly play Omen, but am comfortable with Sova and Cyper as well", user_id: 2, conversation_id: 5},
  {text: "perfect, any of those would be great. let me know your riot ID and ill send you a friend request. ", user_id: 8, conversation_id: 5},
  {text: "sweet its PVCKY #5321", user_id: 2, conversation_id: 5},
  {text: "Hey man, if you still have a spot I main Sage", user_id: 4, conversation_id: 6},
  {text: "sweet lets do it", user_id: 8, conversation_id: 6},
  {text: "why is your avi Breach then lol", user_id: 8, conversation_id: 6},
  {text: "i like his beard lmao. ", user_id: 4, conversation_id: 6},
  {text: "and dope whats your riot ID ill send you a friend request", user_id: 18, conversation_id: 6},
  {text: "lol alright. its philman #5555", user_id: 8, conversation_id: 6},
  {text: "Hey if you still need 1 i play sage! I placed plat 2 but fell to gold 3 from solo q tilt :/", user_id: 7, conversation_id: 7},
  {text: "Hey sorry already got the 2 i posted for, but i can still add you to play if we ever have a spot?", user_id: 8, conversation_id: 7},
  {text: "yes pls add me - caraKat #5432", user_id: 7, conversation_id: 7},
  {text: "sent!", user_id: 8, conversation_id: 7},
  {text: "hi", user_id: 8, conversation_id: 6},
  {text: "hi ", user_id: 8, conversation_id: 7}
])